### ISSUE TITLE
user whatsit code doesn't work

### ISSUE THREAD

**Issue by eroux** [josephwright/ltluatex#2]
Porting [gregorio](https://github.com/gregorio-project/gregorio/tree/master/tex) to the new LaTeX format, it seems the whatsit node is buggy. The line

```
local create_marker = luatexbase.new_user_whatsit('marker', 'gregoriotex')
```

fails with

```

Lua module: gregoriotex 2015/08/26 4.0.0-beta2 GregorioTeX module.
Custom whatsit marker = 1
! LuaTeX error [\directlua]:1: attempt to call global 'newnode' (a nil value)
stack traceback:
        [\directlua]:1: in function 'new_user_whatsit'
        ...io-test/var/texmf/tex/luatex/gregoriotex/gregoriotex.lua:89: in main chunk
        [C]: in function 'require'
        [\directlua]:1: in main chunk.
\RequireLuaModule #1->\directlua {require("#1")}
                                                \@gobbleoptarg 
l.126 \RequireLuaModule{gregoriotex}
                                  %
? 
! Emergency stop.
```

and looking at the code of [luatexbase](https://github.com/josephwright/ltluatexsupp/blob/master/luatexbase/luatexbase.dtx), `newnode` is indeed used without being defined. I think this is also the case of `copynode` and maybe a few others.

**Comment by josephwright** [comment]
Fixed by https://github.com/josephwright/ltluatexsupp/commit/7cf9fd498e980e008b053ae6df960097a01d3df6.
