### ISSUE TITLE
luatexbase.get_module_version is nil

### ISSUE THREAD

**Issue by henryso** [josephwright/ltluatex#3]
I am working with @eroux on porting gregorio-project/gregorio to use the new latex/luatexbase.  After applying the fixes for #2, I am getting the following error:

```
! LuaTeX error ...io-test/var/texmf/tex/luatex/gregoriotex/gregoriotex.lua:217: 
attempt to call field 'get_module_version' (a nil value)
stack traceback:
        ...io-test/var/texmf/tex/luatex/gregoriotex/gregoriotex.lua:217: in function 'i
nit'
        [\directlua]:1: in main chunk.
```

Line 217 in gregoriotex.lua is

```
local mcb_version = luatexbase.get_module_version('luatexbase-mcb')
```

Am I missing something to require or a new option somewhere?

**Comment by josephwright** [comment]
What's this needed for?

**Comment by henryso** [comment]
This is the complete code block:

```
    local mcb_version = luatexbase.get_module_version('luatexbase-mcb')
    if mcb_version and mcb_version > 0.6 then
      luatexbase.add_to_callback('finish_pdffile', write_greaux,
          'gregoriotex.write_greaux')
    else
      -- The version of luatexbase in TeX Live 2014 does not support it, and
      -- luatexbase prevents a direct call to callback.register.  Because of
      -- this, we lose the LuaTeX statistics and "output written to" messages,
      -- but I know of no other workaround.

      luatexbase.add_to_callback('stop_run', write_greaux,
          'gregoriotex.write_greaux')
    end
```

Basically, we want to hook onto `finish_pdffile` to call `write_greaux`, but it wasn't supported until 0.7 of luatexbase-mcb.

**Comment by davidcarlisle** [comment]
On 3 October 2015 at 15:27, Henry So notifications@github.com wrote:

> This is the complete code block:
> 
> ```
> local mcb_version = luatexbase.get_module_version('luatexbase-mcb')
> if mcb_version and mcb_version > 0.6 then
>   luatexbase.add_to_callback('finish_pdffile', write_greaux,
>       'gregoriotex.write_greaux')
> else
>   -- The version of luatexbase in TeX Live 2014 does not support it, and
>   -- luatexbase prevents a direct call to callback.register.  Because of
>   -- this, we lose the LuaTeX statistics and "output written to" messages,
>   -- but I know of no other workaround.
> 
>   luatexbase.add_to_callback('stop_run', write_greaux,
>       'gregoriotex.write_greaux')
> end
> ```
> 
> Basically, we want to hook onto finish_pdffile to call write_greaux, but
> it wasn't supported until 0.7 of luatexbase-mcb.
> 
> —

I'm not sure I understand, in the new version there are not separate
submodules so no real version for luatexbase-mcb even if there was a
get_version function, but if this version of gregorio is written for (or at
least it knows it is running on) the new luatexbase  then can't you just do

```
  luatexbase.add_to_callback('finish_pdffile', write_greaux,
      'gregoriotex.write_greaux')
```

what does this test tell you ?

```
if mcb_version and mcb_version > 0.6 then
```

**Comment by henryso** [comment]
Our objective here is to ensure backwards compatibility, for at least a couple of years.  Should I check for the existence of get_module_version and use that to decide that the system is running this version of luatexbase?  Is there a better test?

If checking for the non-existence of get_module_version is the best way to detect this version of luatexbase, then that's what I will do, and this issue can be closed.

**Comment by davidcarlisle** [comment]
On 3 October 2015 at 17:04, Henry So notifications@github.com wrote:

> Our objective here is to ensure backwards compatibility, for at least a
> couple of years. Should I check for the existence of get_module_version and
> use that to decide that the system is running this version of luatexbase?
> Is there a better test?
> 
> If checking for the non-existence of get_module_version is the best way to
> detect this version of luatexbase, then that's what I will do, and this
> issue can be closed.

something like that, from the tex side of things we tend to use
\ifx\newluafunction  to test for the new code
from lua as you say you can pick any function that you know is in or  not
in the new code and test for that

I could add a get_module_version function to the new luatexbase but I'm not
sure it would help here as the -mcb module
isn't there at all, and I'm not sure it's worth faking all the submodules
just for this. (I could be persuaded though
on compatibility grounds....)

So if you're happy to do a direct test for the new code rather than
insisting on perfect compatibility here I'd rather close with no action.

David

**Comment by henryso** [comment]
I'm happy to just check for the non-existence of get_module_version.  Thank you.
