### ISSUE TITLE
log functions from luatexbase.provides_module no longer treat arguments as string.format

### ISSUE THREAD

**Issue by henryso** [josephwright/ltluatex#4]
In porting gregorio-project/gregorio to use the new latex/luatexbase, I noticed that the log functions from luatexbase.provides_module no longer treat their arguments as string.format and instead only print the first argument verbatim.  I can update all references in gregorio to call string.format instead, but I wanted to be sure that this is the new, correct behavior before doing that.  Is it?

**Comment by davidcarlisle** [comment]
On 3 October 2015 at 15:24, Henry So notifications@github.com wrote:

> In porting gregorio-project/gregorio to use the new latex/luatexbase, I
> noticed that the log functions from luatexbase.provides_module no longer
> treat their arguments as string.format and instead only print the first
> argument verbatim. I can update all references in gregorio to call
> string.format instead, but I wanted to be sure that this is the new,
> correct behavior before doing that. Is it?
> 
> —

I think we want the verbatim version in ltluatex, but luatexbase emulation
ought to do better here,
I think  changing luatexbase.sty to say

```
function luatexbase.errwarinf(name)
    return
    function(s,...) return luatexbase.module_error(name, s:format(...)) end,
    function(s,...) return luatexbase.module_warning(name, s:format(...))
end,
    function(s,...) return luatexbase.module_info(name, s:format(...)) end,
    function(s,...) return luatexbase.module_info(name, s:format(...)) end
end
```

probably does what you need here?

at least this works for me

```
local err, warning, info, log = luatexbase.provides_module({name="wibble"})

log(" this is [\@percentchar 3.4f]", 55)
```

producing

```
Module wibble Info:  this is [55.0000] on input line 12
```

**Comment by henryso** [comment]
Yes, that would surely work for us.

**Comment by davidcarlisle** [comment]
On 3 October 2015 at 16:06, Henry So notifications@github.com wrote:

> Yes, that would surely work for us.

Ok I'll push something to the documented sources in a bit..

David

> —
> Reply to this email directly or view it on GitHub
> https://github.com/josephwright/ltluatexsupp/issues/4#issuecomment-145255520
> .

## 

http://dpcarlisle.blogspot.com/

**Comment by davidcarlisle** [comment]
see commit 938d81d

**Comment by henryso** [comment]
For what it's worth, I am fine with this fix.

**Comment by davidcarlisle** [comment]
Glad to be of service:-) Let us know if gregorio shows up any more issues!
