### ISSUE TITLE
ltluatex.tex: Missing number, treated as zero.

### ISSUE THREAD

**Issue by adunning** [josephwright/ltluatex#5]
On a fresh installation of BasicTeX 2015 on OS X 10.11 with `collection-luatex` installed, and everything updated, `luatex` does not seem to be fully operational. Using this as a test document, with the command `lualatex test.tex`:

``` tex
\documentclass{article}
\usepackage{luacode}

\begin{document}
A random number:
\begin{luacode}
  tex.print(math.random())
\end{luacode}
\end{document}
```

The output is as follows:

```
This is LuaTeX, Version beta-0.80.0 (TeX Live 2015) (rev 5238) 
 restricted \write18 enabled.
(./test.tex
LaTeX2e <2015/01/01>
Babel <3.9l> and hyphenation patterns for 21 languages loaded.
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2015basic/texmf-dist/tex/lualatex/luacode/luacode.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/generic/oberdiek/ifluatex.sty)
(/usr/local/texlive/2015basic/texmf-dist/tex/luatex/luatexbase/luatexbase.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/luatex/ctablestack/ctablestack.sty
(/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/ltluatex.tex
! Missing number, treated as zero.
<to be read again> 
\relax 
l.140 \newcatcodetable\catcodetable@initex
```

The offending file is 2015/10/02 v1.0e. I apologize in advance if this isn't the correct place to report this, or if there's something obvious I am overlooking.

**Comment by josephwright** [comment]
I'm not seeing this with an up-to-date system (I have to deliberately force use of the 2015/01/01 kernel). Adding `\listfiles` I get

```
 *File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
 luacode.sty    2012/01/23 v1.2a lua-in-tex helpers (mpg)
ifluatex.sty    2010/03/01 v1.3 Provides the ifluatex switch (HO)
luatexbase.sty    2015/10/03 v1.2 luatexbase interface to LuaTeX 
ctablestack.sty    2015/10/01 v1.0 Catcode table stable support
ltluatex.tex    2015/10/02 v1.0e LuaTeX support for plain TeX (core) 
unicode-letters.def
```

plus for LaTeX itself

```
LaTeX2e <2015/01/01> patch level 2
```

Could you add your `\listfiles` output?

(BTW, as your kernel version isn't showing a patch level it looks like its a bit behind the current release. Ideally, run `tlmgr update --self --all --no-auto-install`, which should get you the latest LaTeX kernel.)

**Comment by adunning** [comment]
It looks as if there's something strange going on with TeX Live rather than your package; I'm very sorry about this. I am running `tlmgr update --self --all --reinstall-forcibly-removed --no-auto-install` and for good measure `tlmgr backup --clean --all`. I cannot get to the file list, since loading anything Lua-related produces the above error; but checking the files manually verifies that they are the most recent. Yet it's still indicating that it's running the earlier LaTeX, as well as Babel 3.9l, even though 3.9m has been installed. There is no other TeX installation on my system, so I do not understand how this can be. Should I write the MacTeX people about this?

**Comment by davidcarlisle** [comment]
seems odd,  what does

kpsewhich latex.ltx report?

should be

/usr/local/texlive/2015basic/texmf-dist/tex/latex/base/

and what version is in that file (the format could be older than the source
if something went wrong during an update)

it should have the following in an installation updated via tlmgr

%%% From File: ltvers.dtx
\def\fmtname{LaTeX2e}
\edef\fmtversion
   {2015/10/01}
\def\patch@level{1}

David

**Comment by adunning** [comment]
Thanks for the suggestion; my installation matches that exactly. What I find particularly odd is that the same thing happened after uninstalling the entire thing and reloading it from the most recent package.

I do note that none of the binaries in `/usr/local/texlive/2015basic/bin/x86_64-darwin` has a date newer than 12 May 2015; is that normal?

**Comment by davidcarlisle** [comment]
binaries don't update so often but in my texlive 2015 (cygwin) setup I have
around 10 binaries newer than May of this year, in particular  luajittex
that updated the other day:

-rwxr-xr-x 1 zzz zzz  9615872 Sep 27 22:57 luajittex.exe

(doesn't necessarily mean the mac binaries updated though:-)

but it sounds like you have an up to date latex source file but the format
has not been remade
which is strange.

fmtutil-sys --all

probably forces them to be remade, but it shouldn't be necessary.

David

**Comment by adunning** [comment]
Running `fmtutil-sys --all` fixed the problem; thank you, and apologies for wasting your time! I assume that this is a bug in MacTeX: I will write them to report.
